# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=5, help_text='The Asset price.')),
                ('existence', models.IntegerField(default=5, help_text='The Asset price.')),
                ('code', models.TextField(help_text='custom_code.')),
                ('product_id', models.IntegerField(default=5, help_text='The Asset price.')),
                ('type', models.TextField(help_text='The assetType name.')),
                ('expires_at', models.DateTimeField()),
                ('duration', models.DurationField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
